### ISSUE TITLE
Store PDF version of paper in repo?

### ISSUE THREAD

**Issue by davidlmobley** [markovmodel/pyemma_tutorials#132]
I think it would be helpful to store a PDF version of the LiveCoMS paper in the repo; I see the tex is here, but if someone wants to read it, they will have to compile it themselves.

**Comment by thempel** [comment]
Good idea. I've included a link to the compiled PDF to the manuscript folder. Also, it's now attached to the [release](https://github.com/markovmodel/pyemma_tutorials/releases) on Github. (We originally didn't include the PDF to the repo because handling binary files with Git can become messy in the long run.) 

@davidlmobley Please let me know if that works for you.
