### ISSUE TITLE
More detailed workflow description

### ISSUE THREAD

**Issue by cwehmeyer** [markovmodel/pyemma_tutorials#147]
The description of the individual steps' significance is not sufficient; examples are

- [x] CK test (#140)
- [x] why are good features important
- [x] what are consequences of bad choices

We need to discuss more what we are aiming for with each step and why we do this.

In my opinion, this should mostly go into the notebooks.

**Comment by thempel** [comment]
Some parts of this issue are addressed in the above mentioned PR #152. In the new manuscript section about large systems we explain why it is important to have a good feature selection and dimension reduction to obtain a good clustering.

**Comment by thempel** [comment]
Some general points regarding the workflow descriptions and where some more explanation could be useful. Please feel free to ignore certain points.

in general: 
- [ ] more links between the notebooks (also, to certain sections) would be very helpful
- [ ] maybe mention if something is repeated from previous notebooks (e.g. loading, discretization etc)
- [ ] later notebooks have more motivation / introduction sections at the beginning as a general intro. I'd say that'd help for the first notebooks, too.

NB01:
case 2
- [ ] why do we add backbone torsion features for first example?
- [ ] since it is discussed: why load instead of source in this example (e.g. link to below section)
- [ ] why VAMP-2 score? connect to "why backbone torsions"
- [ ] motivate a little better why different featurizations are tested

NB02:
case 1:
- [ ] "given the low dimensionality of the data": maybe mention that this, too, might be realistic for certain datasets and that dim reduction is optional in general. 
- [ ] motivate why 2 different clusterings are shown

case 2:
- [ ] mention why we try different features with different projections

NB3:
- [ ] maybe link to theory section or mention that ITS should not depend on the lag time? (mention reason why we look for ITS convergence)

NB4:
case 1:
- [ ] very short motivation why we compute MSM stationary distribution instead of just using a histogram?
- [ ] before showing eigenvectors: mention that they describe the slow processes (in later paragraph we say that they "visualize" the slow processes, maybe that's not an optimal formulation)

case 2:
- [ ] maybe explain a little more what the eigenvector plot means, i.e. what processes we see? 

NB5:
intro:
- [ ] motivate why we do PCCA++

case 2:
- [ ] "We concatenate all three discrete trajectories...": needs a warning sign

general:
- [ ] not really clear why we do this analysis. maybe put more emphasis on "we conduct example analyses", e.g. in intro

NB6:
case 1:
- [ ] first code cells completely lack explanations

general:
- [ ] moves pretty fast with large code blocks; I guess that's okay because it's an advanced section

NB7:
- [ ] motivate why we repeat the pentapeptide analysis here

NB8:
intro:
- [ ] first sentence: "most problems arise" -> "most problems in Markov modeling of MD data arise"

case 1:
- [ ] first example: mention that well-sampled double-well is presented for reference

**Comment by marscher** [comment]
Thanks Tim, I will address the issues in nb01 and 02.
