### ISSUE TITLE
circleci is taking forever

### ISSUE THREAD

**Issue by brookehus** [markovmodel/pyemma_tutorials#177]
Is this still an issue?

**Comment by marscher** [comment]
On 15.11.18 10:53, Brooke Husic wrote:
> Assigned #177 to @marscher.
> 

it is not - the failure Chris talked about, was due to an connection
error to the Anaconda cloud (I guess due to high load).

Here is an overview of the last builds. They are either canceled on
purpose or just succeeded:

https://circleci.com/gh/markovmodel/pyemma_tutorials

**Comment by brookehus** [comment]
Great!
