### ISSUE TITLE
Cosmetic changes to the notebooks

### ISSUE THREAD

**Issue by cwehmeyer** [markovmodel/pyemma_tutorials#37]
Here is a listing of necessary corrections/checks:

- [x] Use concatenation consistently.
- [x] Use consistent notation for concatenated trajectories.
- [x] Use `stride` more effectively in `cluster_kmeans()` to prevent long execution times.
- [x] Check all variables names for consistency.
- [x] Use consistent sizes when plotting figures.
- [x] Check that all exercises are correctly set up.
- [x] Rename/sort the notebooks.
- [x] Prevent or hide warnings.
- [x] Check that all **wrapping up** sections are complete.
- [x] Check all LaTeX strings and replace non-LaTeX strings where applicable.

Feel free to extend this list.

**Comment by thempel** [comment]
**Warnings:**
I've tested all the NBs with the latest pyemma devel version and find the following:

Featurization. Should we fix this in pyemma or is there a way to mute this warning? Concerns **notebooks 01, 02, 05**.
- 16-07-18 14:59:00 pyemma.coordinates.data.featurization.featurizer.MDFeaturizer[23] WARNING  The 1D arrays input for add_distances() have been sorted, and index duplicates have been eliminated.
Check the output of describe() to see the actual order of the features

- 16-07-18 15:00:22 pyemma.coordinates.data.featurization.featurizer.MDFeaturizer[28] WARNING  Using all residue pairs with schemes like closest or closest-heavy is very time consuming. Consider reducing the residue pairs

Another class of warning messages appears in certain CK-tests in **notebook 06 [20, 21, 29]**:
/home/mi/thempel/mystorage/software/pyemma/pyemma/util/statistics.py:60: UserWarning: confidence interval for constant data is not meaningful
  warnings.warn('confidence interval for constant data is not meaningful')

The same warning occurs in and in **07 [21, 22]** because `sample_conf()` is called for `msm.correlation()` which returns a tuple of times and correlations. 

Any ideas on that? The confidence interval warnings are not wrong, but not very useful either... 

Notebook 08 naturally comes with some warnings.

**Comment by thempel** [comment]
> Another class of warning messages appears in certain CK-tests in notebook 06 [20, 21, 29]:
/home/mi/thempel/mystorage/software/pyemma/pyemma/util/statistics.py:60: UserWarning: confidence interval for constant data is not meaningful
warnings.warn('confidence interval for constant data is not meaningful')

> The same warning occurs in and in 07 [21, 22] because sample_conf() is called for msm.correlation() which returns a tuple of times and correlations.

This part is still not resolved and probably requires some changes in pyEMMA.
