### ISSUE TITLE
Proper notebook headers

### ISSUE THREAD

**Issue by cwehmeyer** [markovmodel/pyemma_tutorials#52]
We should clean up the notebook headers and provide some general information, e.g.:
- very brief content/aim description
- license
- maintainer/author(?)

**Comment by thempel** [comment]
@cwehmeyer, you already included the license into all of the notebooks, right?
@marscher @psolsson @cwehmeyer: Should we include maintainer/author?

Finally, let's organize this since it affects all notebooks:

- [ ] 01-data-io-and-featurisation
- [ ] 02-dimension-reduction-and-discretisation
- [ ] 03-msm-estimation-and-validation
- [ ] 04-msm-coarse-graining-and-analysis
- [ ] 05-hidden-markov-state-models
- [ ] 06-expectations-and-observables
- [ ] 07-vamp-based-feature-selection
- [ ] 08-common-problems

**Comment by cwehmeyer** [comment]
> @cwehmeyer, you already included the license into all of the notebooks, right?

Yes the license is included but still a bit messy.

> @marscher @psolsson @cwehmeyer: Should we include maintainer/author?

I think that would be helpful.
