### ISSUE TITLE
Exercises

### ISSUE THREAD

**Issue by franknoe** [markovmodel/pyemma_tutorials#65]
Most of the notebook content on the more interesting systems (e.g. pentapeptide) are in the form of exercises. Is that what is wanted in LiveComs? 

I am not sure if this is ideal. This way we show everything on the most boring system and ask the user to do the interesting stuff themselves. OK in a live PyEMMA school, but I haven't seen that in an online tutorial.

**Comment by cwehmeyer** [comment]
I believe we should use the most simple (boring) systems for showcasing because they do not add complexity when learning the API.

The pentapeptide is more challenging than the double well and alanine dipeptide, but the exercises only ask for repetitions of tasks which have either just been shown (on a simple system) or used several times before in other notebooks. Do you think that using the pentapeptide here would distract too much?

**Comment by cwehmeyer** [comment]
Following up in yesterday's discussion, we will use the pentapeptide example in an exercise-free showcase notebook and remove it from the other notebooks wherever possible.

The alanine dipeptide example will continue to have exercises.
